# AppS3Bucket (XR) - Crossplane v2 style (namespaced XR)
# This is the "claim" object users apply.
apiVersion: storage.example.com/v1alpha1
kind: AppS3Bucket
metadata:
  name: my-s3bucket
  namespace: default
  labels:
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: crossplane
spec:
  # Business / user inputs (these are patched into MRs by the Composition)
  bucketName: team-a-artifacts-20260115
  region: ap-southeast-1
  tags:
    Name: team-a-artifacts-20260115
    Environment: dev
    ManagedBy: crossplane
    Owner: team-a

  # Crossplane v2 machinery must be under spec.crossplane
  crossplane:
    compositionRef:
      name: s3bucket-composition
    # Optional (normally not set by users)
    # compositionRevisionRef:
    #   name: s3bucket-composition-<revision>
    # resourceRefs:
    #   - apiVersion: ...
    #     kind: ...
    #     name: ...
